---
#Ansible Playbook to pull Docker Image from Registry & run Docker container

- import_playbook: build-push-image.yaml

- name: Playbook to build and run Docker
  hosts: docker_host
  gather_facts: false

  tasks:
    - name: Run Docker container using simple-docker-image
      docker_container:
        name: simple-docker-container
        image: <your-docker-hub-username>/simple-docker-image:latest
        state: started
        recreate: yes
        detach: true
        pull: yes
        ports:
          - "8888:8080"